#Catherine Rivas
#Group member:Amirha
library(tidyverse)
install.packages("ggplot2")
load("~/Desktop/RWork/V0500_Lecture1”/BRFSS2022_rev.RData")
xtabs(~ brfss22$ADDEPEV3 + brfss22$SEXVAR)
#proportion of people m/f with depressive disorder 
prop.table(table(brfss22$ADDEPEV3, brfss22$SEXVAR))
 
#code to shorten the length of observations
 NN <- length(brfss22$ADDEPEV3)
set.seed(12345)
restrict_1 <- (runif(NN) < 0.1) # use just 10% 
summary(restrict_1)

 brfss_small <- subset(brfss22, restrict_1)
 library(ggplot2)
 
 ggplot(brfss_small, aes(x = SEXVAR, fill = ADDEPEV3)) + geom_bar()
 
#switching the x and y variables
ggplot(brfss_small, aes(x = ADDEPEV3, fill = SEXVAR)) + geom_bar()

#considering them as a porportion
ggplot(brfss_small, aes(x = SEXVAR, fill = ADDEPEV3)) + geom_bar(position = "fill")
ggplot(brfss_small, aes(x = ADDEPEV3, fill = SEXVAR)) + geom_bar(position = "fill")

#changing color
ggplot(brfss_small, aes(x = SEXVAR, fill = ADDEPEV3)) + geom_bar(position = "fill") + scale_fill_viridis_d()
ggplot(brfss_small, aes(x = ADDEPEV3, fill = SEXVAR)) + geom_bar(position = "fill") + scale_fill_viridis_d(option="plasma")


#three way comparison
brfss_small_m <- subset(brfss_small,brfss_small$SEXVAR == "Male")
brfss_small_f <- subset(brfss_small,brfss_small$SEXVAR == "Female")

#all the previous graphs
ggplot(brfss_small_f, aes(x = ADDEPEV3, fill = EXERANY2)) + geom_bar(position = "fill") + scale_fill_viridis_d(option="rocket")

#Midpoint
brfss22$Age_midpt <- fct_recode(brfss22$X_AGEG5YR, "21" = "Age 18 to 24",
                                "27" = "Age 25 to 29", "32" = "Age 30 to 34",
                                "37" = "Age 35 to 39", "42" = "Age 40 to 44",
                                "47" = "Age 45 to 49", "52" = "Age 50 to 54",
                                "57" = "Age 55 to 59", "62" = "Age 60 to 64",
                                "67" = "Age 65 to 69", "72" = "Age 70 to 74",
                                "77" = "Age 75 to 79", "82" = "Age 80 or older",
                                NULL = "Dont know/Refused/Missing")

summary(brfss22$Age_midpt)
brfss22$Age_midpt <- as.numeric(levels(brfss22$Age_midpt))[brfss22$Age_midpt]
summary(brfss22$Age_midpt) # note the diff!
ggplot(d_sleeptime, aes(x = SLEPTIM1) ) + geom_histogram()
ggplot(d_sleeptime, aes(x = SLEPTIM1) ) + geom_histogram(binwidth = 1)
sleep_gg <- ggplot(d_sleeptime, aes(x = SLEPTIM1) )
sleep_gg + geom_histogram(binwidth = 2)
sleep_gg + geom_histogram(binwidth = 3)
sleep_gg + geom_histogram(binwidth = 4)
sleep_gg + geom_histogram(bins = 10)
sleep_gg + geom_freqpoly(binwidth = 2)
sleep_gg + geom_histogram(color = "blue", fill="yellow")
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
sleep_gg + geom_histogram(binwidth = 1) + geom_vline(aes(xintercept = mean(SLEPTIM1)), linetype="dashed", linewidth=1)
sleep_age_gg <- ggplot(d_sleeptime_age, aes(SLEPTIM1, Age_midpt)) 
sleep_age_gg + geom_point(alpha = 0.05)
sleep_age_gg + geom_point(alpha = 0.05) + geom_density2d()
sleep_age_gg +   stat_density_2d(aes(fill = stat(level)), geom = 'polygon') +
  scale_fill_viridis_c(name = "density") +
  geom_point(shape = '.')
  ## Warning: `stat(level)` was deprecated in ggplot2 3.4.0.
## ℹ Please use `after_stat(level)` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
sleep_age_gg + stat_density_2d(aes(fill = after_stat(density)), geom = 'raster', contour = FALSE) +       
  scale_fill_viridis_c() +
  coord_cartesian(expand = FALSE) +
  geom_point(shape = '.', col = 'white')

#First steps
 library(ggplot2)
 library(tidyverse)
#using new variables
summary(brfss22) 

#finding the name of the variables 
names(brfss22)

#Depression and ethnicity 
> xtabs(~ brfss22$ADDEPEV3 + brfss22$X_HISPANC)

#PP table for depression and ethinicity 
> prop.table(table(brfss22$X_HISPANC, brfss22$SEXVAR))
  
#ggplot graph of depression and ethnicity 
ggplot(brfss_small, aes(x = X_HISPANC, fill = ADDEPEV3)) + geom_bar()

#switching the x and y variables 
ggplot(brfss_small, aes(x = ADDEPEV3, fill = X_HISPANC)) + geom_bar()

#condsidering them as a porportion
ggplot(brfss_small, aes(x = ADDEPEV3, fill = X_HISPANC)) + geom_bar(position = "fill")
ggplot(brfss_small, aes(x = X_HISPANC, fill = ADDEPEV3)) + geom_bar(position = "fill")

#Changing Color 
ggplot(brfss_small, aes(x = X_HISPANC, fill = ADDEPEV3)) + geom_bar(position = "fill") + scale_fill_viridis_d()
ggplot(brfss_small, aes(x = ADDEPEV3, fill = SEXVAR)) + geom_bar(position = "fill") + scale_fill_viridis_d(option="plasma")


library(ggplot2)
library(tidyverse)
#other variables
names(brfss22)

#One thing that I found intesting is that the majority of the people that don't identify as Hispanic smoke marijuana while there was a much smaller number of those that identify as hispaic and smoke. I personaly think that smoking is correlated to depression so it was also interestig to see that there were more people who had no been told have depressive disorder and are hispanic. But that could also be that they were misdiagnosed. 





